version: '2.2'

services:
  ns:
    build: ns
    image: ${DOCKER_REGISTRY}desec/desec-ns:latest
    init: true
    ports:
    - "5300:53"
    - "5300:53/udp"  # TODO those are debugging ports
    networks:
      front:
        ipv4_address: 10.16.0.2
        ipv6_address: ${DESEC_NS_IPV6_ADDRESS}
    volumes:
    - zones:/zones  # TODO make readonly
    - ./rundir:/rundir
    - knotsocket:/rundir/knot
    logging:
      driver: "syslog"
      options:
        tag: "desec-ns/ns"
    restart: unless-stopped

  replicator:
    # TODO talk to prometheus
    build: replicator
    image: desec/replicator:latest
    init: true
    depends_on:
    - ns
    environment:
    - DESEC_NS_APIKEY
    - DESECSTACK_DOMAIN
    - DESECSTACK_SSH_KNOWN_HOST
    volumes:
    - replicator_keys:/root/.ssh
    - zones:/zones
    - knotsocket:/rundir/knot
    logging:
      driver: "syslog"
      options:
        tag: "desec-ns/replicator"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    init: true
    ports:
    - "127.0.0.1:9090:9090"
    volumes:
    - ./prometheus/conf:/etc/prometheus:ro
    - prometheus:/prometheus
    logging:
      driver: "syslog"
      options:
        tag: "desec-ns/prometheus"
    restart: unless-stopped

volumes:
  prometheus:
  replicator_keys:
  zones:
  knotsocket:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  front:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.0.0/24
        gateway: 10.16.0.1
      - subnet: ${DESEC_NS_IPV6_SUBNET}
