version: '2.2'

services:
  db:
    build: db
    image: ${DOCKER_REGISTRY}desec/slave-db:latest
    init: true
    volumes:
    - db_mysql:/var/lib/mysql
    environment:
    - DESECSLAVE_DB_PASSWORD_pdns
    - DESECSLAVE_ID
    - DESECSTACK_DBMASTER
    - DESECSTACK_DBMASTER_USERNAME_replication
    - DESECSTACK_DBMASTER_PASSWORD_replication
    volumes:
    - ${DESECSLAVE_CERT_FOLDER}:/etc/ssl/private
    - db_mysql:/var/lib/mysql
    networks:
      rear:
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/db"
    restart: unless-stopped

  ns:
    build: ns
    image: ${DOCKER_REGISTRY}desec/slave-ns:latest
    init: true
    cap_add:
    - NET_ADMIN
    environment:
    - DESECSLAVE_CARBONSERVER
    - DESECSLAVE_CARBONOURNAME
    - DESECSLAVE_DB_PASSWORD_pdns
    depends_on:
    - db
    networks:
      middle:
        ipv4_address: 172.16.2.2
      rear:
      rearreplication:
        ipv4_address: 172.16.3.3
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/ns"
    restart: unless-stopped

  dnsdist:
    build: dnsdist
    image: ${DOCKER_REGISTRY}desec/slave-dnsdist:latest
    init: true
    depends_on:
    - ns
    ports:
    - "53:53"
    - "53:53/udp"
    networks:
      front:
        ipv4_address: 172.16.0.2
        ipv6_address: ${DESECSLAVE_IPV6_ADDRESS}
      middle:
        ipv4_address: 172.16.2.3
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/dnsdist"
    restart: unless-stopped

  openvpn-client:
    build: openvpn-client
    image: desec/openvpn-client:latest
    init: true
    cap_add:
    - NET_ADMIN
    environment:
    - DESECSTACK_VPN_SERVER
    volumes:
    - ./openvpn-client/secrets:/etc/openvpn/secrets:ro
    networks:
      rearreplication:
        ipv4_address: 172.16.3.2
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/openvpn-client"
    restart: unless-stopped

volumes:
  db_mysql:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  front:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1
      - subnet: ${DESECSLAVE_IPV6_SUBNET}
  middle:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        gateway: 172.16.2.1
  rear:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
  rearreplication:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.3.0/24
        gateway: 172.16.3.1
